/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AdminMenuControllerFindManyParams,
  CreateMenuDto,
  Menu,
  MenuList,
  OkResponseDto,
  UpdateMenuDto
} from '../../model'



  /**
 * @summary 메뉴 목록 조회하기
 */
export const adminMenuControllerFindMany = <TData = AxiosResponse<MenuList>>(
    params?: AdminMenuControllerFindManyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/admin/menu`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary 메뉴 생성하기
 */
export const adminMenuControllerCreate = <TData = AxiosResponse<Menu>>(
    createMenuDto: CreateMenuDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/admin/menu`,
      createMenuDto,options
    );
  }
/**
 * @summary 메뉴 수정하기 또는 활성화 변경
 */
export const adminMenuControllerUpdate = <TData = AxiosResponse<Menu>>(
    id: string,
    updateMenuDto: UpdateMenuDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/admin/menu/${id}`,
      updateMenuDto,options
    );
  }
/**
 * @summary 메뉴 삭제하기
 */
export const adminMenuControllerDelete = <TData = AxiosResponse<OkResponseDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/olhso/admin/menu/${id}`,options
    );
  }
export type AdminMenuControllerFindManyResult = AxiosResponse<MenuList>
export type AdminMenuControllerCreateResult = AxiosResponse<Menu>
export type AdminMenuControllerUpdateResult = AxiosResponse<Menu>
export type AdminMenuControllerDeleteResult = AxiosResponse<OkResponseDto>
