/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AppleOauthDto,
  GoogleOauthDto,
  OAuthRes
} from '../../model'



  /**
 * @summary Apple 소셜로그인 요청
 */
export const clientOauthControllerApple = <TData = AxiosResponse<OAuthRes>>(
    appleOauthDto: AppleOauthDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/client-oauth/apple`,
      appleOauthDto,options
    );
  }
/**
 * @summary Google 소셜로그인 요청
 */
export const clientOauthControllerGoogle = <TData = AxiosResponse<OAuthRes>>(
    googleOauthDto: GoogleOauthDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/client-oauth/google`,
      googleOauthDto,options
    );
  }
export const clientOauthControllerFacebook = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/client-oauth/facebook`,undefined,options
    );
  }
export type ClientOauthControllerAppleResult = AxiosResponse<OAuthRes>
export type ClientOauthControllerGoogleResult = AxiosResponse<OAuthRes>
export type ClientOauthControllerFacebookResult = AxiosResponse<void>
