/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  PreSignedUrl,
  UserFileUrlReq
} from '../../model'



  /**
 * @summary 파일 업로드를 위한 AWS S3 pre-signed url을 반환
 */
export const fileControllerCreatePreSignedUrl = <TData = AxiosResponse<PreSignedUrl[]>>(
    userFileUrlReq: UserFileUrlReq, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/files/upload-urls`,
      userFileUrlReq,options
    );
  }
export type FileControllerCreatePreSignedUrlResult = AxiosResponse<PreSignedUrl[]>
