/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  MainPictureControllerFindManyParams,
  MainPictureList
} from '../../model'



  /**
 * @summary 메인 이미지 조회하기
 */
export const mainPictureControllerFindMany = <TData = AxiosResponse<MainPictureList>>(
    params?: MainPictureControllerFindManyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/main-picture`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export type MainPictureControllerFindManyResult = AxiosResponse<MainPictureList>
