/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreateTruckStockForServerDto,
  TruckStockForServer,
  TruckStockForServerControllerFindManyParams,
  TruckStockForServerList,
  UpdateTruckStockForServerDto
} from '../../model'



  /**
 * @summary 서비스를 위한 전체 트럭 재고 목록 조회
 */
export const truckStockForServerControllerFindMany = <TData = AxiosResponse<TruckStockForServerList>>(
    params?: TruckStockForServerControllerFindManyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/trucks/stock-for-server`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary 서비스를 위한 트럭 재고 삭제
 */
export const truckStockForServerControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/olhso/trucks/stock-for-server/${id}`,options
    );
  }
/**
 * @summary 서비스를 위한 트럭에 적재된 재고 목록 조회
 */
export const truckStockForServerControllerFindManyByTruckId = <TData = AxiosResponse<TruckStockForServerList>>(
    truckId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/trucks/${truckId}/stock-for-server`,options
    );
  }
/**
 * @summary 서비스를 위한 트럭 재고 생성
 */
export const truckStockForServerControllerCreate = <TData = AxiosResponse<TruckStockForServer>>(
    truckId: string,
    createTruckStockForServerDto: CreateTruckStockForServerDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/trucks/${truckId}/stock-for-server`,
      createTruckStockForServerDto,options
    );
  }
/**
 * @summary 서비스를 위한 트럭에 적재된 재고 상세 조회
 */
export const truckStockForServerControllerFindOne = <TData = AxiosResponse<TruckStockForServerList>>(
    truckId: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/trucks/${truckId}/stock-for-server/${id}`,options
    );
  }
/**
 * @summary 서비스를 위한 트럭 재고 수정
 */
export const truckStockForServerControllerUpdate = <TData = AxiosResponse<TruckStockForServer>>(
    truckId: string,
    id: string,
    updateTruckStockForServerDto: UpdateTruckStockForServerDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/trucks/${truckId}/stock-for-server/${id}`,
      updateTruckStockForServerDto,options
    );
  }
export type TruckStockForServerControllerFindManyResult = AxiosResponse<TruckStockForServerList>
export type TruckStockForServerControllerRemoveResult = AxiosResponse<void>
export type TruckStockForServerControllerFindManyByTruckIdResult = AxiosResponse<TruckStockForServerList>
export type TruckStockForServerControllerCreateResult = AxiosResponse<TruckStockForServer>
export type TruckStockForServerControllerFindOneResult = AxiosResponse<TruckStockForServerList>
export type TruckStockForServerControllerUpdateResult = AxiosResponse<TruckStockForServer>
