/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreateTruckDriverNotiDto,
  OkResponseDto
} from '../../model'



  /**
 * @summary 트럭 운전자의 Noti 토큰 등록
 */
export const truckDriverNotiControllerCreate = <TData = AxiosResponse<OkResponseDto>>(
    createTruckDriverNotiDto: CreateTruckDriverNotiDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/truck-driver-noti`,
      createTruckDriverNotiDto,options
    );
  }
/**
 * @summary 트럭 운전자의 Noti 토큰 삭제
 */
export const truckDriverNotiControllerDelete = <TData = AxiosResponse<OkResponseDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/olhso/truck-driver-noti`,options
    );
  }
export type TruckDriverNotiControllerCreateResult = AxiosResponse<OkResponseDto>
export type TruckDriverNotiControllerDeleteResult = AxiosResponse<OkResponseDto>
