/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreateReviewDto,
  ReturnReviewObjectList,
  Review
} from '../../model'



  /**
 * @summary 주문에 맞는 리뷰 항목 정보 보내주기
 */
export const clientReviewControllerFindReviewObject = <TData = AxiosResponse<ReturnReviewObjectList>>(
    orderId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/client-review/order/${orderId}`,options
    );
  }
/**
 * @summary 리뷰 작성하기
 */
export const clientReviewControllerCreate = <TData = AxiosResponse<Review>>(
    orderId: string,
    createReviewDto: CreateReviewDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/client-review/order/${orderId}`,
      createReviewDto,options
    );
  }
export type ClientReviewControllerFindReviewObjectResult = AxiosResponse<ReturnReviewObjectList>
export type ClientReviewControllerCreateResult = AxiosResponse<Review>
