/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AvailableReservationControllerGetAvailableReservationSlotListParams,
  AvailableSlotList,
  ReservationStatusDto
} from '../../model'



  /**
 * @summary 예약 가능한 슬롯 조회
 */
export const availableReservationControllerGetAvailableReservationSlotList = <TData = AxiosResponse<AvailableSlotList[]>>(
    params?: AvailableReservationControllerGetAvailableReservationSlotListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/available-reservation`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary 시스템의 예약주문 기능 활성화 여부 조회
 */
export const availableReservationControllerFindReservationStatus = <TData = AxiosResponse<ReservationStatusDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/available-reservation/status`,options
    );
  }
export type AvailableReservationControllerGetAvailableReservationSlotListResult = AxiosResponse<AvailableSlotList[]>
export type AvailableReservationControllerFindReservationStatusResult = AxiosResponse<ReservationStatusDto>
