/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  DownTimeBodyDto,
  TruckDriverDownTime
} from '../../model'



  /**
 * @summary down-time 데이터를 생성합니다. 알맞은 downTimeType을 선택해주세요. (PAUSED, EMERGENCY)
 */
export const truckDriverDownTimeControllerCreate = <TData = AxiosResponse<TruckDriverDownTime>>(
    driverId: string,
    downTimeBodyDto: DownTimeBodyDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/truck-drivers/${driverId}/down-time`,
      downTimeBodyDto,options
    );
  }
/**
 * @summary downTimeType이 PAUSED 경우에 10분 간 DownTime을 연장합니다
 */
export const truckDriverDownTimeControllerAddPausedTime = <TData = AxiosResponse<TruckDriverDownTime>>(
    driverId: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/truck-drivers/${driverId}/down-time/${id}/extend`,undefined,options
    );
  }
/**
 * @summary downTimeType이 PAUSED 경우에만 DownTime이 끝난 시간을 기록합니다
 */
export const truckDriverDownTimeControllerUpdate = <TData = AxiosResponse<TruckDriverDownTime>>(
    driverId: string,
    id: string,
    downTimeBodyDto: DownTimeBodyDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/truck-drivers/${driverId}/down-time/${id}`,
      downTimeBodyDto,options
    );
  }
export type TruckDriverDownTimeControllerCreateResult = AxiosResponse<TruckDriverDownTime>
export type TruckDriverDownTimeControllerAddPausedTimeResult = AxiosResponse<TruckDriverDownTime>
export type TruckDriverDownTimeControllerUpdateResult = AxiosResponse<TruckDriverDownTime>
