/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AnnounceBarControllerFindManyParams,
  AnnounceBarList
} from '../../model'



  /**
 * @summary 공지사항 목록 조회하기
 */
export const announceBarControllerFindMany = <TData = AxiosResponse<AnnounceBarList>>(
    params?: AnnounceBarControllerFindManyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/announce-bar`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export type AnnounceBarControllerFindManyResult = AxiosResponse<AnnounceBarList>
