/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  OkResponseDto,
  TruckWokStatus,
  TruckWokStatusUpdateDto
} from '../../model'



  /**
 * @summary 트럭의 Wok 상태 조회
 */
export const truckWokStatusControllerGetWokStatus = <TData = AxiosResponse<TruckWokStatus[]>>(
    truckId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/trucks/${truckId}/wok-status`,options
    );
  }
/**
 * @summary Wok fixable 상태 변경, status: OK -> wok 고친 경우, status: UNAVAILABLE -> wok 못고친 경우
 */
export const truckWokStatusControllerChangeWokStatus = <TData = AxiosResponse<OkResponseDto>>(
    truckId: string,
    id: string,
    truckWokStatusUpdateDto: TruckWokStatusUpdateDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/trucks/${truckId}/wok-status/${id}`,
      truckWokStatusUpdateDto,options
    );
  }
export type TruckWokStatusControllerGetWokStatusResult = AxiosResponse<TruckWokStatus[]>
export type TruckWokStatusControllerChangeWokStatusResult = AxiosResponse<OkResponseDto>
