/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AdminMenuOptionControllerFindManyParams,
  MenuOptionList
} from '../../model'



  /**
 * @summary 메뉴 옵션 정보 불러오기
 */
export const adminMenuOptionControllerFindMany = <TData = AxiosResponse<MenuOptionList>>(
    params?: AdminMenuOptionControllerFindManyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/admin/menu-option`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export type AdminMenuOptionControllerFindManyResult = AxiosResponse<MenuOptionList>
