/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  TruckArea
} from '../../model'



  /**
 * @summary 트럭 운행 지역 목록 모두 조회
 */
export const truckAreaControllerFindAllTruckAreas = <TData = AxiosResponse<TruckArea[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/truck-areas`,options
    );
  }
export type TruckAreaControllerFindAllTruckAreasResult = AxiosResponse<TruckArea[]>
