/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreatePhoneVerificationDto,
  CreateVerificationDto,
  EmailVerificationDto,
  PhoneVerificationDto,
  UserModel,
  VerifiedCode,
  VerifiedEmail
} from '../../model'



  /**
 * @summary 디코딩된 id_token을 json으로 반환
 */
export const authControllerMe = <TData = AxiosResponse<UserModel>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/auth/me`,options
    );
  }
/**
 * @summary 이메일 인증코드 생성 후 발송
 */
export const authControllerCreateEmailVerification = <TData = AxiosResponse<void>>(
    createVerificationDto: CreateVerificationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/auth/email-verification`,
      createVerificationDto,options
    );
  }
/**
 * @summary 이메일 인증 결과를 반환
 */
export const authControllerVerifyEmail = <TData = AxiosResponse<VerifiedCode>>(
    emailVerificationDto: EmailVerificationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/auth/email-verification`,
      emailVerificationDto,options
    );
  }
/**
 * @summary 휴대전화 인증코드 생성 후 발송
 */
export const authControllerCreateFindEmailVerification = <TData = AxiosResponse<void>>(
    createPhoneVerificationDto: CreatePhoneVerificationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/auth/find-email`,
      createPhoneVerificationDto,options
    );
  }
/**
 * @summary 휴대전화 인증 결과를 반환
 */
export const authControllerVerifyPhone = <TData = AxiosResponse<VerifiedEmail[]>>(
    phoneVerificationDto: PhoneVerificationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/auth/find-email`,
      phoneVerificationDto,options
    );
  }
export type AuthControllerMeResult = AxiosResponse<UserModel>
export type AuthControllerCreateEmailVerificationResult = AxiosResponse<void>
export type AuthControllerVerifyEmailResult = AxiosResponse<VerifiedCode>
export type AuthControllerCreateFindEmailVerificationResult = AxiosResponse<void>
export type AuthControllerVerifyPhoneResult = AxiosResponse<VerifiedEmail[]>
