/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AdminReviewAnswerControllerFindManyParams,
  ReviewAnswerList
} from '../../model'



  /**
 * @summary 리뷰 선택지 목록 조회하기
 */
export const adminReviewAnswerControllerFindMany = <TData = AxiosResponse<ReviewAnswerList>>(
    params?: AdminReviewAnswerControllerFindManyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/admin/review-answer`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export type AdminReviewAnswerControllerFindManyResult = AxiosResponse<ReviewAnswerList>
