/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  PromotionBannerControllerFindManyParams,
  PromotionBannerList
} from '../../model'



  /**
 * @summary 프로모션 배너 조회하기
 */
export const promotionBannerControllerFindMany = <TData = AxiosResponse<PromotionBannerList>>(
    params?: PromotionBannerControllerFindManyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/promotion-banner`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export type PromotionBannerControllerFindManyResult = AxiosResponse<PromotionBannerList>
