/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  SendCodeDto,
  VerifyCodeDto
} from '../../model'



  export const smsControllerSendSms = <TData = AxiosResponse<void>>(
    sendCodeDto: SendCodeDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/sms`,
      sendCodeDto,options
    );
  }
export const smsControllerVerifySms = <TData = AxiosResponse<void>>(
    verifyCodeDto: VerifyCodeDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/sms/verify`,
      verifyCodeDto,options
    );
  }
export type SmsControllerSendSmsResult = AxiosResponse<void>
export type SmsControllerVerifySmsResult = AxiosResponse<void>
