/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ClientAddr,
  CreateClientAddrDto,
  OkResponseDto
} from '../../model'



  /**
 * @summary 사용자 주소 목록 불러오기. 대표주소가 최상단으로 정렬됩니다.
 */
export const clientAddrControllerAddrInfo = <TData = AxiosResponse<ClientAddr[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/client-addr`,options
    );
  }
/**
 * @summary 사용자 주소 등록하기, Primary는 false로 자동 생성됩니다. PUT 요청으로 primary를 지정해주세요.
 */
export const clientAddrControllerCreate = <TData = AxiosResponse<ClientAddr>>(
    createClientAddrDto: CreateClientAddrDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/client-addr`,
      createClientAddrDto,options
    );
  }
/**
 * @summary 대표주소 지정하기
 */
export const clientAddrControllerChangePrimary = <TData = AxiosResponse<ClientAddr[]>>(
    addrId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/client-addr/primary/${addrId}`,undefined,options
    );
  }
/**
 * @summary 주소 삭제하기
 */
export const clientAddrControllerDelete = <TData = AxiosResponse<OkResponseDto>>(
    addrId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/olhso/client-addr/${addrId}`,options
    );
  }
export type ClientAddrControllerAddrInfoResult = AxiosResponse<ClientAddr[]>
export type ClientAddrControllerCreateResult = AxiosResponse<ClientAddr>
export type ClientAddrControllerChangePrimaryResult = AxiosResponse<ClientAddr[]>
export type ClientAddrControllerDeleteResult = AxiosResponse<OkResponseDto>
