/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ClientCard,
  ClientCardList,
  CreateClientCardDto
} from '../../model'



  /**
 * @summary 카드 정보 조회
 */
export const adminClientCardControllerFindOne = <TData = AxiosResponse<ClientCard>>(
    clientId: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/admin/client/${clientId}/cards/${id}`,options
    );
  }
/**
 * @summary 카드 제거 후 남은 카드 목록 반환
 */
export const adminClientCardControllerRemove = <TData = AxiosResponse<ClientCardList>>(
    clientId: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/olhso/admin/client/${clientId}/cards/${id}`,options
    );
  }
/**
 * @summary primary 카드로 지정 후 전체 카드 목록 반환
 */
export const adminClientCardControllerChangeToPrimary = <TData = AxiosResponse<ClientCardList>>(
    clientId: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/admin/client/${clientId}/cards/${id}/primary`,undefined,options
    );
  }
/**
 * @summary 클라이언트의 카드 목록 조회
 */
export const adminClientCardControllerMyCards = <TData = AxiosResponse<ClientCardList>>(
    clientId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/admin/client/${clientId}/cards`,options
    );
  }
/**
 * @summary 클라이언트 카드 생성
 */
export const adminClientCardControllerCreateMyCard = <TData = AxiosResponse<ClientCard>>(
    clientId: string,
    createClientCardDto: CreateClientCardDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/admin/client/${clientId}/cards`,
      createClientCardDto,options
    );
  }
export type AdminClientCardControllerFindOneResult = AxiosResponse<ClientCard>
export type AdminClientCardControllerRemoveResult = AxiosResponse<ClientCardList>
export type AdminClientCardControllerChangeToPrimaryResult = AxiosResponse<ClientCardList>
export type AdminClientCardControllerMyCardsResult = AxiosResponse<ClientCardList>
export type AdminClientCardControllerCreateMyCardResult = AxiosResponse<ClientCard>
