/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Menu,
  MenuControllerFindManyParams,
  MenuControllerFindManyPublicParams,
  MenuList
} from '../../model'



  /**
 * @summary 비회원의 메뉴 목록 조회하기
 */
export const menuControllerFindManyPublic = <TData = AxiosResponse<MenuList>>(
    params?: MenuControllerFindManyPublicParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/menu/public`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary 메뉴 목록 조회하기
 */
export const menuControllerFindMany = <TData = AxiosResponse<MenuList>>(
    params?: MenuControllerFindManyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/menu`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary 단일 메뉴 가져오기
 */
export const menuControllerFindOne = <TData = AxiosResponse<Menu>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/menu/${id}`,options
    );
  }
export type MenuControllerFindManyPublicResult = AxiosResponse<MenuList>
export type MenuControllerFindManyResult = AxiosResponse<MenuList>
export type MenuControllerFindOneResult = AxiosResponse<Menu>
