/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AdminOrderControllerFindManyParams,
  AdminOrderControllerFindTotalDetail2Params,
  AdminOrderControllerFindTotalDetailParams,
  CancelOrderDto,
  OkResponseDto,
  OrderList
} from '../../model'



  /**
 * @summary 관리자 페이지에서 주문 목록 조회하기
 */
export const adminOrderControllerFindMany = <TData = AxiosResponse<OrderList>>(
    params?: AdminOrderControllerFindManyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/admin/order`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary 관리자 페이지에서 주문 취소하기
 */
export const adminOrderControllerUpdate = <TData = AxiosResponse<OkResponseDto>>(
    id: string,
    cancelOrderDto: CancelOrderDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/admin/order/${id}`,
      cancelOrderDto,options
    );
  }
/**
 * @summary 기간별 총 주문 수와 총 메뉴 수 금액까지 조회하기
 */
export const adminOrderControllerFindTotalDetail = <TData = AxiosResponse<void>>(
    params: AdminOrderControllerFindTotalDetailParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/admin/order/total`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary 기간별 총 주문 수와 총 메뉴 수 금액까지 조회하기
 */
export const adminOrderControllerFindTotalDetail2 = <TData = AxiosResponse<void>>(
    params: AdminOrderControllerFindTotalDetail2Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/admin/order/total-test-2`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export type AdminOrderControllerFindManyResult = AxiosResponse<OrderList>
export type AdminOrderControllerUpdateResult = AxiosResponse<OkResponseDto>
export type AdminOrderControllerFindTotalDetailResult = AxiosResponse<void>
export type AdminOrderControllerFindTotalDetail2Result = AxiosResponse<void>
