/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { SortOrder } from './sortOrder';
import type { DiscountType } from './discountType';
import type { PromotionType } from './promotionType';

export type AdminCouponControllerFindManyParams = {
sortOrder?: SortOrder[];
sortBy?: string[];
discountType?: DiscountType;
promotionType?: PromotionType;
title?: string;
description?: string;
activated?: boolean;
};
