/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { SortOrder } from './sortOrder';
import type { OrderSortBy } from './orderSortBy';
import type { AdminReserveOrderControllerFindManyReceiveType } from './adminReserveOrderControllerFindManyReceiveType';

export type AdminReserveOrderControllerFindManyParams = {
sortOrder?: SortOrder[];
sortBy?: OrderSortBy[];
clientId?: string;
startDate?: string;
endDate?: string;
startDateTime?: string;
endDateTime?: string;
customerAddr?: string;
clientEmail?: string;
clientPhoneNum?: string;
receiveType?: AdminReserveOrderControllerFindManyReceiveType;
cancellation?: boolean;
confirmed?: boolean;
sendToLive?: boolean;
};
