/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { SortOrder } from './sortOrder';
import type { AdminOrderControllerFindManyReceiveType } from './adminOrderControllerFindManyReceiveType';
import type { AdminOrderControllerFindManyCookingStatus } from './adminOrderControllerFindManyCookingStatus';
import type { AdminOrderControllerFindManyDeliveryStatus } from './adminOrderControllerFindManyDeliveryStatus';

export type AdminOrderControllerFindManyParams = {
sortOrder?: SortOrder[];
sortBy?: string[];
clientId?: string;
startDate?: string;
endDate?: string;
customerAddr?: string;
clientEmail?: string;
clientPhoneNum?: string;
receiveType?: AdminOrderControllerFindManyReceiveType;
cancellation?: boolean;
cookingStatus?: AdminOrderControllerFindManyCookingStatus;
deliveryStatus?: AdminOrderControllerFindManyDeliveryStatus;
driverId?: string;
truckId?: string;
estDeliveryFinishedTime?: string;
};
