/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { SortOrder } from './sortOrder';
import type { AdminReviewQuestionControllerFindManyType } from './adminReviewQuestionControllerFindManyType';

export type AdminReviewQuestionControllerFindManyParams = {
sortOrder?: SortOrder[];
sortBy?: string[];
isActive?: boolean;
type?: AdminReviewQuestionControllerFindManyType;
};
