/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { SortOrder } from './sortOrder';

export type AdminTruckDriverControllerFindManyParams = {
sortOrder?: SortOrder[];
sortBy?: string[];
email?: string;
phoneNum?: string;
lastName?: string;
firstName?: string;
note?: string;
status?: string;
};
