/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type AdminOrderControllerFindManyCookingStatus = typeof AdminOrderControllerFindManyCookingStatus[keyof typeof AdminOrderControllerFindManyCookingStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminOrderControllerFindManyCookingStatus = {
  DISPATCH_WAITING: 'DISPATCH_WAITING',
  COOKING_WAITING: 'COOKING_WAITING',
  COOKING: 'COOKING',
  FINISH: 'FINISH',
} as const;
