/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export interface AdminCreateUseDto {
  clientId: string;
  /** 포인트 - cent 단위 양수. ex) $1 = 100 */
  point: number;
}
