/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { SortOrder } from './sortOrder';
import type { NotiAdminPath } from './notiAdminPath';

export type AdminNotiControllerFindManyParams = {
sortOrder?: SortOrder[];
sortBy?: string[];
startDate?: string;
endDate?: string;
time?: string;
path?: NotiAdminPath;
isActive?: boolean;
};
