/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type AdminReviewQuestionControllerFindManyType = typeof AdminReviewQuestionControllerFindManyType[keyof typeof AdminReviewQuestionControllerFindManyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminReviewQuestionControllerFindManyType = {
  MENU: 'MENU',
  PUBLIC: 'PUBLIC',
  DELIVERY: 'DELIVERY',
} as const;
