/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type AdminReserveOrderControllerFindManyReceiveType = typeof AdminReserveOrderControllerFindManyReceiveType[keyof typeof AdminReserveOrderControllerFindManyReceiveType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminReserveOrderControllerFindManyReceiveType = {
  FACE_TO_FACE: 'FACE_TO_FACE',
  LEAVE_AT_DOOR: 'LEAVE_AT_DOOR',
} as const;
