/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { TruckDriver } from './truckDriver';
import type { AnnounceBarToImage } from './announceBarToImage';

export interface AnnounceBar {
  announceTitle: string;
  body: string;
  createdAt: string;
  createdBy: TruckDriver;
  endAt: string;
  footer?: string;
  header?: string;
  id: string;
  images?: AnnounceBarToImage[];
  isActive: boolean;
  priority: number;
  startAt: string;
  title: string;
  updatedAt: string;
  updatedBy: TruckDriver;
}
