/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { AnnounceBar } from './announceBar';
import type { FileObject } from './fileObject';

export interface AnnounceBarToImage {
  announceBar: AnnounceBar;
  createdAt: string;
  id: string;
  image: FileObject;
  priority: number;
  updatedAt: string;
}
