/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type AutoWokStatus = typeof AutoWokStatus[keyof typeof AutoWokStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AutoWokStatus = {
  OK: 'OK',
  FIXABLE: 'FIXABLE',
  UNAVAILABLE: 'UNAVAILABLE',
  NONE: 'NONE',
} as const;
