/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type AvailableReservationControllerGetAvailableReservationSlotListParams = {
/**
 * startDate와 endDate를 동일하게 입력할 경우 해당 날짜 하루에 대해 조회
 */
startDate?: string;
endDate?: string;
};
