/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type BoardType = typeof BoardType[keyof typeof BoardType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BoardType = {
  NOTICE: 'NOTICE',
  FAQ: 'FAQ',
  HELP: 'HELP',
  EVENT: 'EVENT',
  TERMS_AND_POLICIES: 'TERMS_AND_POLICIES',
  ETC: 'ETC',
} as const;
