/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { Client } from './client';
import type { TruckDriver } from './truckDriver';
import type { BoardType } from './boardType';

export interface Board {
  activated: boolean;
  client?: Client;
  content?: string;
  createdAt: string;
  driver?: TruckDriver;
  id: string;
  order?: number;
  title: string;
  type: BoardType;
  updatedAt: string;
}
