/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { CancelOrderDtoDeliveryStatus } from './cancelOrderDtoDeliveryStatus';

export interface CancelOrderDto {
  cancellation: boolean;
  deliveryStatus: CancelOrderDtoDeliveryStatus;
  driverId?: string;
  truckId?: string;
}
