/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type CancelOrderDtoDeliveryStatus = typeof CancelOrderDtoDeliveryStatus[keyof typeof CancelOrderDtoDeliveryStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CancelOrderDtoDeliveryStatus = {
  DELIVERING: 'DELIVERING',
  FINISH: 'FINISH',
  UNRECEIVED: 'UNRECEIVED',
  DRIVER_EMERGENCY: 'DRIVER_EMERGENCY',
  TRUCK_BREAKDOWN: 'TRUCK_BREAKDOWN',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  NO_TRUCKS: 'NO_TRUCKS',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  WOK_UNAVAILABLE: 'WOK_UNAVAILABLE',
  PARTIAL_REFUND: 'PARTIAL_REFUND',
  ADMIN_REFUND: 'ADMIN_REFUND',
  ADMIN_CANCEL: 'ADMIN_CANCEL',
  CANCEL: 'CANCEL',
} as const;
