/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type CardBrand = typeof CardBrand[keyof typeof CardBrand];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CardBrand = {
  amex: 'amex',
  diners: 'diners',
  discover: 'discover',
  eftpos_au: 'eftpos_au',
  jcb: 'jcb',
  mastercard: 'mastercard',
  unionpay: 'unionpay',
  visa: 'visa',
  unknown: 'unknown',
} as const;
