/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export interface CheckAvailableTimeDto {
  clientAddrId: string;
  orderDate: string;
  reserveTime: string;
  /** 현재 TimeZone 값 */
  timeZone: string;
}
