/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { CardBrand } from './cardBrand';

export interface ClientCard {
  brand: CardBrand;
  createdAt: string;
  expMonth: number;
  expYear: number;
  id: string;
  isActive: boolean;
  last4: string;
  paymentMethodId: string;
  primary: boolean;
  updatedAt: string;
  zipCode: string;
}
