/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type ClientOrderControllerMyOrdersFindOrderType = typeof ClientOrderControllerMyOrdersFindOrderType[keyof typeof ClientOrderControllerMyOrdersFindOrderType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientOrderControllerMyOrdersFindOrderType = {
  DESTINATION: 'DESTINATION',
  COMPLETED: 'COMPLETED',
} as const;
