/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export interface ClientPointRes {
  /** 남은 포인트 수량. cent 단위. 나누기 100해서 출력 */
  point: number;
}
