/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export interface Client {
  acceptMarketing: boolean;
  acceptNotification: boolean;
  createdAt: string;
  email: string;
  firstName?: string;
  id: string;
  isActive: boolean;
  lastName?: string;
  phoneNum?: string;
  phoneNumVerified: boolean;
  point: number;
  updatedAt: string;
}
