/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { SortOrder } from './sortOrder';
import type { DiscountType } from './discountType';
import type { QueryPromotionType } from './queryPromotionType';
import type { MyCouponStatus } from './myCouponStatus';

export type ClientCouponControllerFindMyCouponsParams = {
sortOrder?: SortOrder[];
sortBy?: string[];
discountType?: DiscountType;
promotionType?: QueryPromotionType;
status?: MyCouponStatus;
menuIds?: string[];
};
