/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type ClientReserveOrderControllerGetAvailableReservationSlotListParams = {
/**
 * 현재 TimeZone 값
 */
timeZone: string;
clientAddrId: string;
};
