/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { PointEventType } from './pointEventType';
import type { PointItemType } from './pointItemType';
import type { MainItemRes } from './mainItemRes';
import type { StripeStatus } from './stripeStatus';

export interface ClientPointEvent {
  amount?: number;
  couponAmount?: number;
  createdAt: string;
  driverBenefitFee?: number;
  eventType: PointEventType;
  id: string;
  itemType?: PointItemType;
  orderId?: string;
  orderItems?: MainItemRes[];
  point: number;
  reserveOrderId?: string;
  status?: StripeStatus;
  subTotal?: number;
  tax?: number;
  tip?: number;
  usePointAmount?: number;
}
