/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { TruckArea } from './truckArea';

export interface ClientAddr {
  addr: string;
  addrDetail?: string;
  buildingName?: string;
  createdAt: string;
  id: string;
  lat: number;
  lng: number;
  primary: boolean;
  truckArea?: TruckArea;
  updatedAt: string;
  zipCode?: number;
}
