/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { Coupon } from './coupon';
import type { PaginationMeta } from './paginationMeta';

export interface CouponList {
  items: Coupon[];
  meta: PaginationMeta;
}
