/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { DiscountType } from './discountType';
import type { PromotionType } from './promotionType';

export interface CreateCouponDto {
  activated?: boolean;
  description?: string;
  /** dollar 단위. 소수점 이하 2자리 초과 시 절삭 */
  discountAmount?: number;
  discountMenuId?: string;
  /** 소수점 이하 1자리 초과 시 절삭 */
  discountRatio?: number;
  discountType: DiscountType;
  expiration?: string;
  expirationTime?: string;
  /** dollar 단위. 소수점 이하 2자리 초과 시 절삭 */
  minPayAmount?: number;
  promotionType: PromotionType;
  quantity?: number;
  startDate?: string;
  startTime?: string;
  title: string;
}
