/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type CreateNotiAdminDtoPath = typeof CreateNotiAdminDtoPath[keyof typeof CreateNotiAdminDtoPath];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateNotiAdminDtoPath = {
  HOME: 'HOME',
  PAST_ORDERS: 'PAST_ORDERS',
  ORDERS: 'ORDERS',
  REWARDS: 'REWARDS',
  COUPON: 'COUPON',
} as const;
