/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type CreateTruckDriverDtoStatus = typeof CreateTruckDriverDtoStatus[keyof typeof CreateTruckDriverDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTruckDriverDtoStatus = {
  WORKING: 'WORKING',
  OFF: 'OFF',
} as const;
