/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { CreateNotiAdminDtoPath } from './createNotiAdminDtoPath';

export interface CreateNotiAdminDto {
  body: string;
  endDate: string;
  path: CreateNotiAdminDtoPath;
  startDate: string;
  time: string;
  title: string;
}
