/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { OrderItem } from './orderItem';
import type { ReceiveType } from './receiveType';

export interface CreateReserveOrderDto {
  clientAddrId: string;
  clientCardId: string;
  clientPhoneNum: string;
  couponId?: string;
  customerAddr: string;
  driverTip: number;
  lat: number;
  lng: number;
  note?: string;
  orderDate: string;
  orderItems: OrderItem[];
  receiveType: ReceiveType;
  reserveTime: string;
  /** 현재 TimeZone 값 */
  timeZone: string;
  usePointAmount: number;
}
