/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { MainItem } from './mainItem';
import type { ReceiveType } from './receiveType';

export interface CreateOrderDto {
  areaId: string;
  clientAddrId?: string;
  clientCardId: string;
  clientPhoneNum: string;
  couponId?: string;
  customerAddr: string;
  driverTip: number;
  lat: number;
  lng: number;
  note?: string;
  orderItems: MainItem[];
  receiveType: ReceiveType;
  usePointAmount: number;
}
