/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export interface CreateClientAddrDto {
  addr: string;
  addrDetail: string;
  areaId: string;
  buildingName: string;
  lat: number;
  lng: number;
  zipCode: number;
}
