/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { CreateTruckDtoDrivingStatus } from './createTruckDtoDrivingStatus';
import type { CreateTruckDtoVehicleStatus } from './createTruckDtoVehicleStatus';

export interface CreateTruckDto {
  distance?: number;
  drivingStatus?: CreateTruckDtoDrivingStatus;
  licensePlateNumber: string;
  name?: string;
  note?: string;
  truckAreaIds?: string[];
  truckSlotArrayId: string;
  usedWoks: number;
  vehicleStatus?: CreateTruckDtoVehicleStatus;
}
