/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { MainItem } from './mainItem';

export interface CreateOrderPaymentDto {
  areaId?: string;
  clientAddrId?: string;
  clientCardId?: string;
  couponId?: string;
  driverTip: number;
  orderItems: MainItem[];
  usePointAmount: number;
}
