/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { MenuType } from './menuType';

export interface CreateMenuDto {
  allergyList?: string[];
  cookingTime?: number;
  description?: string;
  kcal?: number;
  menuOptions?: string[];
  menuSeq?: number;
  name: string;
  nameKor?: string;
  pictureId?: string;
  price: number;
  questions?: string[];
  requireCooking?: boolean;
  servedContent?: string;
  type: MenuType;
}
