/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type CreateTruckDriverDtoRoles = typeof CreateTruckDriverDtoRoles[keyof typeof CreateTruckDriverDtoRoles];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTruckDriverDtoRoles = {
  DRIVER: 'DRIVER',
  MANAGER: 'MANAGER',
  ADMIN: 'ADMIN',
  CLIENT: 'CLIENT',
} as const;
