/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type DiscountType = typeof DiscountType[keyof typeof DiscountType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DiscountType = {
  RATIO: 'RATIO',
  FIXED: 'FIXED',
} as const;
