/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type DownTimeType = typeof DownTimeType[keyof typeof DownTimeType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DownTimeType = {
  PAUSED: 'PAUSED',
  EMERGENCY: 'EMERGENCY',
} as const;
