/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { Client } from './client';
import type { FindManyForClientAppDtoCookingStatus } from './findManyForClientAppDtoCookingStatus';
import type { FileObject } from './fileObject';
import type { MainItemRes } from './mainItemRes';
import type { PaymentTransaction } from './paymentTransaction';
import type { Review } from './review';

export interface FindManyForClientAppDto {
  cancellation: boolean;
  client: Client;
  cookingStatus: FindManyForClientAppDtoCookingStatus;
  deliveryPic?: FileObject;
  estDeliveryFinishedTime: string;
  id: string;
  orderDate: string;
  orderItems: MainItemRes[];
  orderTime: string;
  payment?: PaymentTransaction;
  review?: Review;
}
