/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { OrderItem } from './orderItem';
import type { MainItemSubOptionItem } from './mainItemSubOptionItem';

export interface MainItem {
  menuId: string;
  quantity: number;
  sideMenu?: OrderItem[];
  subOption?: MainItemSubOptionItem[];
}
