/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { SortOrder } from './sortOrder';

export type MainPictureControllerFindManyParams = {
sortOrder?: SortOrder[];
sortBy?: string[];
nowDateTime?: string;
isActive?: boolean;
};
