/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { OrderItemRes } from './orderItemRes';
import type { MainItemResSubOptionItem } from './mainItemResSubOptionItem';
import type { MenuType } from './menuType';

export interface MainItemRes {
  amount?: number;
  menuId: string;
  name?: string;
  price?: number;
  quantity: number;
  sideMenu?: OrderItemRes[];
  subOption?: MainItemResSubOptionItem[];
  type?: MenuType;
  url?: string;
}
