/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type MyCouponStatus = typeof MyCouponStatus[keyof typeof MyCouponStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MyCouponStatus = {
  USED: 'USED',
  AVAILABLE: 'AVAILABLE',
} as const;
