/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { NotiAdminPathProperty } from './notiAdminPathProperty';

export interface NotiAdmin {
  body: string;
  createdAt: string;
  endDate: string;
  id: string;
  isActive: boolean;
  path: NotiAdminPathProperty;
  startDate: string;
  time: string;
  title: string;
  updatedAt: string;
}
