/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type OrderLongerDurationType = typeof OrderLongerDurationType[keyof typeof OrderLongerDurationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderLongerDurationType = {
  COOKING: 'COOKING',
  MOVING: 'MOVING',
  OPTIMAL_MOVE: 'OPTIMAL_MOVE',
} as const;
