/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { Client } from './client';
import type { OrderCookingStatus } from './orderCookingStatus';
import type { FileObject } from './fileObject';
import type { OrderDeliveryStatus } from './orderDeliveryStatus';
import type { TruckDriver } from './truckDriver';
import type { OrderLongerDurationType } from './orderLongerDurationType';
import type { MainItemRes } from './mainItemRes';
import type { OrderMenu } from './orderMenu';
import type { PaymentTransaction } from './paymentTransaction';
import type { OrderReceiveType } from './orderReceiveType';
import type { Review } from './review';
import type { Truck } from './truck';
import type { TruckArea } from './truckArea';

export interface Order {
  cancellation: boolean;
  client: Client;
  clientPhoneNum: string;
  cookingStartTime?: string;
  cookingStatus: OrderCookingStatus;
  createdAt: string;
  customerAddr: string;
  deliveryPic?: FileObject;
  deliveryStartTime?: string;
  deliveryStatus: OrderDeliveryStatus;
  driver?: TruckDriver;
  driverTip: number;
  estArrivalTime?: string;
  estCookingFinishedTime?: string;
  estDeliveryFinishedTime?: string;
  firstDeliveryFinishedTime?: string;
  id: string;
  isReserved: boolean;
  lastTurnUsedWoks?: number;
  lat: number;
  lng: number;
  longerDurationType?: OrderLongerDurationType;
  note?: string;
  orderDate: string;
  orderItems: MainItemRes[];
  orderMenus: OrderMenu[];
  orderTime: string;
  payment?: PaymentTransaction;
  realArrivalTime?: string;
  realCookingFinishedTime?: string;
  realDeliveryFinishedTime?: string;
  receiveType: OrderReceiveType;
  review?: Review;
  secondTurnStartTime?: string;
  sendToTruck: boolean;
  totalCookingTime?: number;
  totalPrice: number;
  truck?: Truck;
  truckArea?: TruckArea;
  updatedAt: string;
  usePointAmount: number;
}
