/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { OrderItemResSubOptionItem } from './orderItemResSubOptionItem';
import type { MenuType } from './menuType';

export interface OrderItemRes {
  amount?: number;
  menuId: string;
  name?: string;
  price?: number;
  quantity: number;
  subOption?: OrderItemResSubOptionItem[];
  type?: MenuType;
  url?: string;
}
