/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type OrderMenuStatus = typeof OrderMenuStatus[keyof typeof OrderMenuStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderMenuStatus = {
  READY: 'READY',
  START: 'START',
  COOKING_FINISH: 'COOKING_FINISH',
  FINISH: 'FINISH',
} as const;
