/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type OrderSortBy = typeof OrderSortBy[keyof typeof OrderSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderSortBy = {
  orderTime: 'orderTime',
  createdAt: 'createdAt',
} as const;
