/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { FindManyForClientAppDto } from './findManyForClientAppDto';
import type { PaginationMeta } from './paginationMeta';

export interface OrderListForClientApp {
  items: FindManyForClientAppDto[];
  meta: PaginationMeta;
}
