/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { ClientCard } from './clientCard';

export interface PaymentPreviewRes {
  /** 단위: cent. amount = Total */
  amount: number;
  /** 단위: cent. usePointAmount + couponAmount = promotion */
  couponAmount?: number;
  descriptions: string[];
  /** 단위: cent. tax + driverBenefitFee = Taxes&Other fees */
  driverBenefitFee?: number;
  paymentMethod: ClientCard;
  /** 단위: cent */
  subTotal?: number;
  /** 단위: cent.  tax + driverBenefitFee = Taxes&Other fees */
  tax?: number;
  /** 단위: cent */
  tip?: number;
  /** 단위: cent. usePointAmount + couponAmount = promotion */
  usePointAmount?: number;
}
