/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { ClientCard } from './clientCard';
import type { StripeStatus } from './stripeStatus';

export interface PaymentTransaction {
  amount: number;
  cancelledAt?: string;
  couponAmount?: number;
  createdAt: string;
  driverBenefitFee?: number;
  id: string;
  paidAt?: string;
  paymentMethod?: ClientCard;
  receiptUrl?: string;
  refundAmount?: number;
  refundedAt?: string;
  status: StripeStatus;
  subTotal?: number;
  tax?: number;
  tip?: number;
  updatedAt: string;
  usePointAmount?: number;
}
