/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { PointEventType } from './pointEventType';
import type { PointItemType } from './pointItemType';

export interface PointEvent {
  createdAt: string;
  eventType: PointEventType;
  id: string;
  itemType?: PointItemType;
  point: number;
}
