/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type PointEventType = typeof PointEventType[keyof typeof PointEventType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PointEventType = {
  EARN: 'EARN',
  USE: 'USE',
  EXPIRED: 'EXPIRED',
  CANCEL_USE: 'CANCEL_USE',
  CANCEL_EARN: 'CANCEL_EARN',
} as const;
