/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type PointItemType = typeof PointItemType[keyof typeof PointItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PointItemType = {
  REWARD: 'REWARD',
  ADMIN: 'ADMIN',
} as const;
