/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type PromotionType = typeof PromotionType[keyof typeof PromotionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PromotionType = {
  TOTAL: 'TOTAL',
  MENU: 'MENU',
} as const;
