/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { FileObject } from './fileObject';
import type { PromotionBanner } from './promotionBanner';

export interface PromotionBannerToImage {
  createdAt: string;
  id: string;
  image: FileObject;
  priority: number;
  promotionBanner: PromotionBanner;
  updatedAt: string;
}
