/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type ReceiveType = typeof ReceiveType[keyof typeof ReceiveType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReceiveType = {
  FACE_TO_FACE: 'FACE_TO_FACE',
  LEAVE_AT_DOOR: 'LEAVE_AT_DOOR',
} as const;
