/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type RequestType = typeof RequestType[keyof typeof RequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestType = {
  FINISH: 'FINISH',
  START: 'START',
} as const;
