/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { ReserveOrder } from './reserveOrder';
import type { PaginationMeta } from './paginationMeta';

export interface ReserveOrderList {
  items: ReserveOrder[];
  meta: PaginationMeta;
}
