/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { ReturnDeliveryQuestionDto } from './returnDeliveryQuestionDto';
import type { ReturnMenuQuestionDto } from './returnMenuQuestionDto';
import type { ReturnPublicQuestionDto } from './returnPublicQuestionDto';

export interface ReturnReviewObjectList {
  deliveryQuestion: ReturnDeliveryQuestionDto;
  menuQuestion: ReturnMenuQuestionDto[];
  publicQuestion: ReturnPublicQuestionDto;
}
