/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { ReviewAnswer } from './reviewAnswer';
import type { Order } from './order';

export interface Review {
  answer: ReviewAnswer[];
  createdAt: string;
  id: string;
  note?: string;
  order: Order;
  updatedAt: string;
}
