/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type ReviewAnswerType = typeof ReviewAnswerType[keyof typeof ReviewAnswerType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReviewAnswerType = {
  STAR: 'STAR',
  THREE_OPTION: 'THREE_OPTION',
  TWO_OPTION: 'TWO_OPTION',
} as const;
