/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { ReviewAnswer } from './reviewAnswer';
import type { QuestionType } from './questionType';

export interface ReviewQuestion {
  answer: ReviewAnswer;
  createdAt: string;
  description: string;
  id: string;
  isActive: boolean;
  menus?: string[];
  type: QuestionType;
  updatedAt: string;
}
