/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { Item } from './item';
import type { ReviewAnswerType } from './reviewAnswerType';

export interface ReviewAnswer {
  createdAt: string;
  id: string;
  items: Item[];
  type: ReviewAnswerType;
  updatedAt: string;
}
