/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { ReviewAnswer } from './reviewAnswer';
import type { PaginationMeta } from './paginationMeta';

export interface ReviewAnswerList {
  items: ReviewAnswer[];
  meta: PaginationMeta;
}
