/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export type StripeStatus = typeof StripeStatus[keyof typeof StripeStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StripeStatus = {
  requires_confirmation: 'requires_confirmation',
  requires_action: 'requires_action',
  processing: 'processing',
  requires_capture: 'requires_capture',
  canceled: 'canceled',
  canceled_refund: 'canceled_refund',
  succeeded: 'succeeded',
  refunded: 'refunded',
  partial_refund: 'partial_refund',
} as const;
