/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { TruckDriverAssignment } from './truckDriverAssignment';
import type { TruckModalAssignment } from './truckModalAssignment';
import type { TruckDriverDownTime } from './truckDriverDownTime';
import type { FileObject } from './fileObject';
import type { Role } from './role';
import type { TrucDriverStatus } from './trucDriverStatus';

export interface TruckDriverWithPausedAssignmentDto {
  activated: boolean;
  assignment?: TruckDriverAssignment;
  createdAt: string;
  email: string;
  firstName?: string;
  id: string;
  lastName?: string;
  modalAssignment?: TruckModalAssignment[];
  note?: string;
  pausedAssignment?: TruckDriverDownTime;
  phoneNum: string;
  profileImage?: FileObject;
  roles: Role[];
  status: TrucDriverStatus;
  updatedAt: string;
}
