/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { SortOrder } from './sortOrder';

export type TruckControllerFindManyParams = {
sortOrder?: SortOrder[];
sortBy?: string[];
licensePlateNumber?: string;
name?: string;
note?: string;
drivingStatus?: string;
vehicleStatus?: string;
};
