/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { Order } from './order';
import type { AutoWokStatus } from './autoWokStatus';
import type { Truck } from './truck';

export interface TruckWokStatus {
  createdAt: string;
  id: string;
  order?: Order;
  status: AutoWokStatus;
  truck: Truck;
  updatedAt: string;
  wokNum: number;
}
