/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { TruckDriver } from './truckDriver';
import type { Truck } from './truck';
import type { TruckDriverDownTime } from './truckDriverDownTime';
import type { TruckEvent } from './truckEvent';

export interface TruckDriverDriving {
  createdAt: string;
  driver: TruckDriver;
  endTime?: string;
  finishedDistance?: number;
  id: string;
  lastDrivingStatus?: unknown;
  startDistance?: number;
  startTime?: string;
  truck: Truck;
  truckDriverDownTimes?: TruckDriverDownTime[];
  truckEvents?: TruckEvent[];
  updatedAt: string;
  workingDate: string;
}
