/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { TruckArea } from './truckArea';

export interface TruckZone {
  createdAt: string;
  id: string;
  name: string;
  reservationActive: boolean;
  reservationLimit: number;
  truckAreas: TruckArea[];
  updatedAt: string;
}
