/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { DownTimeType } from './downTimeType';
import type { TruckDriver } from './truckDriver';
import type { TruckDriverDriving } from './truckDriverDriving';

export interface TruckDriverDownTime {
  createdAt: string;
  downTimeType: DownTimeType;
  driver: TruckDriver;
  endDownTime: string;
  estDrivingStartTime?: string;
  id: string;
  startDownTime: string;
  truckDriverDriving?: TruckDriverDriving;
  updatedAt: string;
  workingDate: string;
}
