/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { TruckDriverDriving } from './truckDriverDriving';
import type { PaginationMeta } from './paginationMeta';

export interface TruckDriverDrivingList {
  items: TruckDriverDriving[];
  meta: PaginationMeta;
}
