/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { ReserveOrderStocksDtoForBulkUpdate } from './reserveOrderStocksDtoForBulkUpdate';
import type { TruckStocksDtoForBulkUpdate } from './truckStocksDtoForBulkUpdate';

export interface UpdateTruckStocksBulkForTruckDto {
  reserveOrderStocksArr: ReserveOrderStocksDtoForBulkUpdate[];
  truckStocksArr: TruckStocksDtoForBulkUpdate[];
}
