/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { UpdateTruckDtoDrivingStatus } from './updateTruckDtoDrivingStatus';
import type { UpdateTruckDtoVehicleStatus } from './updateTruckDtoVehicleStatus';

export interface UpdateTruckDto {
  distance?: number;
  drivingStatus?: UpdateTruckDtoDrivingStatus;
  licensePlateNumber?: string;
  name?: string;
  note?: string;
  truckAreaIds?: string[];
  truckSlotArrayId?: string;
  usedWoks?: number;
  vehicleStatus?: UpdateTruckDtoVehicleStatus;
}
