/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { UpdateReviewQuestionDtoType } from './updateReviewQuestionDtoType';

export interface UpdateReviewQuestionDto {
  answerId?: string;
  description?: string;
  isActive: boolean;
  type?: UpdateReviewQuestionDtoType;
}
