/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { UserType } from './userType';

export interface UserModel {
  cognitoUsername: string;
  email: string;
  email_verified?: boolean;
  id: string;
  nickname?: string;
  phone_number?: string;
  phone_number_verified?: boolean;
  roles?: string[];
  type: UserType;
  uuid?: string;
}
