/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */

export interface UserFileUrlReq {
  /** 생성할 pre-signed url의 개수 */
  count: number;
  /** https://{media-cloudfront-host}/{directory}/{fileId}형태로 파일을 서비스하게 됨 */
  directory?: string;
}
