/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreateTruckStockForTruckDto,
  TruckStockForTruck,
  TruckStockForTruckControllerFindManyParams,
  TruckStockForTruckList,
  UpdateTruckStockForTruckDto
} from '../../model'



  /**
 * @summary 전체 트럭 재고 목록 조회
 */
export const truckStockForTruckControllerFindMany = <TData = AxiosResponse<TruckStockForTruckList>>(
    params?: TruckStockForTruckControllerFindManyParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/trucks/stock-for-truck`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary 트럭 재고 삭제
 */
export const truckStockForTruckControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/olhso/trucks/stock-for-truck/${id}`,options
    );
  }
/**
 * @summary 트럭에 적재된 재고 목록 조회
 */
export const truckStockForTruckControllerFindManyByTruckId = <TData = AxiosResponse<TruckStockForTruck[]>>(
    truckId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/trucks/${truckId}/stock-for-truck`,options
    );
  }
/**
 * @summary 트럭에 재고 적재
 */
export const truckStockForTruckControllerCreate = <TData = AxiosResponse<TruckStockForTruck>>(
    truckId: string,
    createTruckStockForTruckDto: CreateTruckStockForTruckDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/olhso/trucks/${truckId}/stock-for-truck`,
      createTruckStockForTruckDto,options
    );
  }
/**
 * @summary 트럭에 적재된 재고 상세 조회
 */
export const truckStockForTruckControllerFindOne = <TData = AxiosResponse<TruckStockForTruck>>(
    truckId: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/trucks/${truckId}/stock-for-truck/${id}`,options
    );
  }
/**
 * @summary 트럭에 적재된 재고 수정
 */
export const truckStockForTruckControllerUpdate = <TData = AxiosResponse<TruckStockForTruck>>(
    truckId: string,
    id: string,
    updateTruckStockForTruckDto: UpdateTruckStockForTruckDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/olhso/trucks/${truckId}/stock-for-truck/${id}`,
      updateTruckStockForTruckDto,options
    );
  }
export type TruckStockForTruckControllerFindManyResult = AxiosResponse<TruckStockForTruckList>
export type TruckStockForTruckControllerRemoveResult = AxiosResponse<void>
export type TruckStockForTruckControllerFindManyByTruckIdResult = AxiosResponse<TruckStockForTruck[]>
export type TruckStockForTruckControllerCreateResult = AxiosResponse<TruckStockForTruck>
export type TruckStockForTruckControllerFindOneResult = AxiosResponse<TruckStockForTruck>
export type TruckStockForTruckControllerUpdateResult = AxiosResponse<TruckStockForTruck>
